### ISSUE TITLE
Create Log-In Page

### ISSUE THREAD

**Issue by aleong2002** [agiledev-students-fall2023/4-final-project-music-ranking-system#26]
Does not need authentification yet. Should be a dummy page that you can click and lead you to the homepage feed. Should also lead to sign up page.

this is related to user story #5 and #6

**Comment by MarekKundla** [comment]
Can I start working on this as my first PR ?

**Comment by aleong2002** [comment]
> Can I start working on this as my first PR ?

Hi, sorry this is a school project so we can't allow you to make an PR/contributions. Thank you for offering though!
